---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.13.0'
- 'pip install cfn-lint==0.11.1'
script:
- 'yamllint module.yml'
- 'cfn-lint -i W3002 -t module.yml'
- 'grep -q "LICENSE-2.0" module.yml'
