---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.19.0'
- 'pip install cfn-lint==0.25.3'
script:
- 'yamllint module.yml'
- 'cfn-lint -i W3002 -t module.yml'
- 'grep -q "LICENSE-2.0" module.yml'
