---
language: python
python:
- '2.7'
install:
- 'pip install yamllint'
- 'pip install cfn-lint'
script:
- 'yamllint module.yml'
- 'cfn-lint -i W3002 -t module.yml'
- 'grep -q "LICENSE-2.0" module.yml'
